import { useEffect, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import axios from "axios";
import { FlaskConical } from "lucide-react";
import ConfidenceBadge from "../components/ui/ConfidenceBadge";
import type { Case } from "../types";

interface IncomingCase {
  case_id: string;
}

export default function TestForgePage() {
  const location = useLocation();
  const navigate = useNavigate();
  const qc = useQueryClient();
  const incoming = location.state as IncomingCase | null;
  const [autoGenerateStatus, setAutoGenerateStatus] = useState<"pending" | "done" | "error" | null>(
    incoming ? "pending" : null
  );

  const { data: cases = [] } = useQuery<Case[]>({
    queryKey: ["cases"],
    queryFn: () => axios.get("/api/cases/").then((r) => r.data),
    refetchInterval: 4000,
  });
  // Every resolved confirmed_bug — whether or not it already has a test. Clicking
  // a row (re)generates the test from that case's existing diagnosis and
  // resolution steps, no manual entry needed.
  const readyForTest = cases.filter(
    (c) => c.category === "confirmed_bug" && (c.status === "approved" || c.status === "resolved")
  );

  // Generates the test AND persists it onto the case AND drafts a KB article —
  // all server-side in one call, so every completion path (this button, Resolve,
  // Approve & Send) consistently ends with a searchable KB article.
  const createTestForCase = useMutation({
    mutationFn: (c: Case) =>
      axios.post<Case>(`/api/cases/${c.id}/generate-test`).then((r) => r.data),
    onSuccess: (updated) => {
      qc.invalidateQueries({ queryKey: ["cases"] });
      navigate(`/cases/${updated.id}`);
    },
  });

  const autoGeneratedRef = useRef(false);
  useEffect(() => {
    if (incoming && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      axios
        .post<Case>(`/api/cases/${incoming.case_id}/generate-test`)
        .then(() => {
          qc.invalidateQueries({ queryKey: ["cases"] });
          setAutoGenerateStatus("done");
        })
        .catch(() => setAutoGenerateStatus("error"));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <FlaskConical size={22} className="text-brand-500" /> TestForge
        </h1>
        {incoming && (
          <p className="text-xs text-brand-400 mt-1">
            {autoGenerateStatus === "pending"
              ? `Generating regression test from resolved case ${incoming.case_id}…`
              : autoGenerateStatus === "done"
              ? `Regression test generated from resolved case ${incoming.case_id}`
              : `Could not generate a test for case ${incoming.case_id}`}
          </p>
        )}
        <p className="text-sm text-slate-400 mt-1">
          Turn resolved bugs into regression tests.
        </p>
      </div>

      <div className="card">
        <h2 className="text-sm font-semibold mb-1">Ready for Testing</h2>
        <p className="text-xs text-slate-500 mb-3">
          Click a case to (re)generate its regression test from the existing diagnosis and
          resolution steps — no manual entry needed.
        </p>
        {readyForTest.length === 0 ? (
          <p className="text-sm text-slate-500 py-4 text-center">
            No resolved bugs yet.
          </p>
        ) : (
          <div className="divide-y divide-surface-3">
            {readyForTest.map((c) => {
              const isThisPending =
                createTestForCase.isPending && createTestForCase.variables?.id === c.id;
              const hasTest = !!(c.packet?.regression_test_snippet || c.regression_test_snippet);
              return (
                <button
                  key={c.id}
                  onClick={() => createTestForCase.mutate(c)}
                  disabled={createTestForCase.isPending}
                  className="w-full py-2.5 flex items-center gap-3 text-left hover:bg-surface-3/50 rounded-lg px-2 -mx-2 disabled:opacity-60"
                >
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium truncate">{c.title}</p>
                    <p className="text-xs text-slate-500 mt-0.5">
                      {c.customer || "—"} · {c.product || "—"}
                    </p>
                  </div>
                  {c.packet && <ConfidenceBadge score={c.packet.confidence} showLabel={false} />}
                  <span className="text-xs text-brand-400 flex-shrink-0 w-24 text-right">
                    {isThisPending ? "Testing…" : hasTest ? "Regenerate" : "Test ticket"}
                  </span>
                </button>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
