import { useEffect, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { useMutation, useQuery } from "@tanstack/react-query";
import axios from "axios";
import { FlaskConical, ChevronRight } from "lucide-react";
import ConfidenceBadge from "../components/ui/ConfidenceBadge";
import type { Case } from "../types";

type Tab = "generate" | "triage";

interface IncomingCase {
  bug_title: string;
  bug_description: string;
  fix_description: string;
  case_id: string;
}

export default function TestForgePage() {
  const location = useLocation();
  const navigate = useNavigate();
  const incoming = location.state as IncomingCase | null;

  const { data: cases = [] } = useQuery<Case[]>({
    queryKey: ["cases"],
    queryFn: () => axios.get("/api/cases/").then((r) => r.data),
  });
  const generatedTests = cases.filter(
    (c) => c.category === "confirmed_bug" && c.packet?.regression_test_snippet
  );

  const [tab, setTab] = useState<Tab>("generate");

  // Generate
  const [genForm, setGenForm] = useState({
    bug_title: incoming?.bug_title ?? "Login page crashes on submit",
    bug_description: incoming?.bug_description ?? "TypeError: cannot read properties of undefined reading 'token'",
    fix_description: incoming?.fix_description ?? "Added null check for auth response before accessing token property",
    framework: "pytest",
    case_id: incoming?.case_id ?? "demo-001",
  });

  const genMutation = useMutation({
    mutationFn: (data: typeof genForm) =>
      axios.post("/api/agents/test-forge/generate", data).then((r) => r.data),
  });

  const autoGeneratedRef = useRef(false);
  useEffect(() => {
    if (incoming && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      genMutation.mutate(genForm);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Triage
  const [triageForm, setTriageForm] = useState({
    test_id: "test-42",
    test_name: "test_user_login_success",
    failure_log: `FAILED tests/test_auth.py::test_user_login_success - TimeoutError
  E   playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
  E   Call log:
  E     - waiting for locator('#login-btn')`,
    test_code: "",
  });

  const triageMutation = useMutation({
    mutationFn: (data: typeof triageForm) =>
      axios.post("/api/agents/test-forge/triage", data).then((r) => r.data),
  });

  return (
    <div className="space-y-5 max-w-3xl">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <FlaskConical size={22} className="text-brand-500" /> TestForge
        </h1>
        {incoming && (
          <p className="text-xs text-brand-400 mt-1">
            {genMutation.isPending
              ? `Generating regression test from resolved case ${incoming.case_id}…`
              : genMutation.isSuccess
              ? `Regression test generated from resolved case ${incoming.case_id}`
              : `Pre-filled from resolved case ${incoming.case_id}`}
          </p>
        )}
        <p className="text-sm text-slate-400 mt-1">
          Turn resolved bugs into regression tests. Triage and self-heal broken tests.
        </p>
      </div>

      {generatedTests.length > 0 && (
        <div className="card">
          <h2 className="text-sm font-semibold mb-3">
            Generated Regression Tests ({generatedTests.length})
          </h2>
          <div className="divide-y divide-surface-3">
            {generatedTests.map((c) => (
              <button
                key={c.id}
                onClick={() => navigate(`/cases/${c.id}`)}
                className="w-full py-2.5 flex items-center gap-3 text-left hover:bg-surface-3/50 rounded-lg px-2 -mx-2"
              >
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium truncate">{c.title}</p>
                  <p className="text-xs text-slate-500 mt-0.5">
                    {c.customer || "—"} · {c.product || "—"}
                  </p>
                </div>
                {c.packet && <ConfidenceBadge score={c.packet.confidence} showLabel={false} />}
                <ChevronRight size={16} className="text-slate-500 shrink-0" />
              </button>
            ))}
          </div>
        </div>
      )}

      <div className="flex gap-1 bg-surface-2 p-1 rounded-lg w-fit">
        {(["generate", "triage"] as Tab[]).map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`px-4 py-1.5 rounded-md text-sm font-medium transition-colors ${
              tab === t
                ? "bg-brand-600 text-white"
                : "text-slate-400 hover:text-slate-100"
            }`}
          >
            {t === "generate" ? "Generate Test" : "Triage Failure"}
          </button>
        ))}
      </div>

      {tab === "generate" && (
        <div className="card space-y-3">
          <h2 className="text-sm font-semibold">Bug → Regression Test</h2>
          {(["bug_title", "bug_description", "fix_description"] as const).map((field) => (
            <div key={field}>
              <label className="text-xs text-slate-400 mb-1 block capitalize">
                {field.replace(/_/g, " ")}
              </label>
              <textarea
                rows={field === "bug_title" ? 1 : 2}
                className="w-full bg-surface-3 rounded-lg px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-brand-500 resize-none"
                value={genForm[field]}
                onChange={(e) => setGenForm({ ...genForm, [field]: e.target.value })}
              />
            </div>
          ))}
          <div className="flex items-center gap-3">
            <select
              className="bg-surface-3 rounded-lg px-3 py-2 text-sm outline-none"
              value={genForm.framework}
              onChange={(e) => setGenForm({ ...genForm, framework: e.target.value })}
            >
              {["pytest", "jest", "playwright", "cypress", "junit"].map((f) => (
                <option key={f} value={f}>{f}</option>
              ))}
            </select>
            <button
              onClick={() => genMutation.mutate(genForm)}
              disabled={genMutation.isPending}
              className="btn-primary"
            >
              {genMutation.isPending ? "Generating…" : "Generate Test"}
            </button>
          </div>

          {genMutation.data && (
            <div className="space-y-2 pt-1">
              <div className="flex items-center justify-between">
                <p className="text-xs text-slate-400 font-mono">{genMutation.data.test_file_path}</p>
                <ConfidenceBadge score={genMutation.data.confidence} />
              </div>
              <pre className="bg-surface rounded-lg p-4 text-xs text-emerald-300 font-mono overflow-auto max-h-80">
                {genMutation.data.test_code}
              </pre>
              <p className="text-xs text-slate-500">{genMutation.data.description}</p>
            </div>
          )}
        </div>
      )}

      {tab === "triage" && (
        <div className="card space-y-3">
          <h2 className="text-sm font-semibold">Triage Test Failure</h2>
          {(["test_name", "failure_log", "test_code"] as const).map((field) => (
            <div key={field}>
              <label className="text-xs text-slate-400 mb-1 block capitalize">
                {field.replace(/_/g, " ")}
              </label>
              <textarea
                rows={field === "test_name" ? 1 : 4}
                className="w-full bg-surface-3 rounded-lg px-3 py-2 text-sm font-mono outline-none focus:ring-1 focus:ring-brand-500 resize-none"
                value={triageForm[field]}
                onChange={(e) => setTriageForm({ ...triageForm, [field]: e.target.value })}
              />
            </div>
          ))}
          <button
            onClick={() => triageMutation.mutate(triageForm)}
            disabled={triageMutation.isPending}
            className="btn-primary"
          >
            {triageMutation.isPending ? "Triaging…" : "Triage Failure"}
          </button>

          {triageMutation.data && (
            <div className="bg-surface rounded-lg p-4 space-y-2">
              <div className="flex items-center gap-3">
                <span className="badge-blue capitalize">{triageMutation.data.failure_kind.replace("_", " ")}</span>
                <ConfidenceBadge score={triageMutation.data.confidence} />
              </div>
              <p className="text-sm text-slate-300">{triageMutation.data.explanation}</p>
              {triageMutation.data.healed_locator && (
                <div>
                  <p className="text-xs text-slate-400 mb-1">Healed Locator</p>
                  <code className="text-xs text-emerald-400 bg-surface-3 px-2 py-1 rounded">
                    {triageMutation.data.healed_locator}
                  </code>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
